import Shars.Verification.Utils.ScalarTac
import Shars.Verification.Utils.Notation
import Shars.Verification.Utils.SimpLikeTactics
import Shars.Verification.Utils.StateArray
import Shars.Verification.Utils.List
import Shars.Verification.Utils.Array
import Shars.Verification.Utils.BitVec
import Shars.Verification.Utils.DecideForallLTNested
import Shars.Verification.Utils.UScalar
import Shars.Verification.Utils.Nat
import Shars.Verification.Utils.Vector
