name = "shars"
version = "0.1.0"
defaultTargets = ["Shars"]

[[lean_lib]]
name = "Shars"

[[require]]
name = "aeneas"
git = { url = "https://github.com/ayhon/aeneas", subDir = "backends/lean" }
rev = "c54602cd49422a2e9dfe10447eb50a90ba59f32d"

[[require]]
name = "Sha3"
git = "https://github.com/ayhon/sha3.lean"
rev = "6a3fbab9edcdbf7c304d87790264eceb452325f3"
